name: news_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_svg: ^1.1.6
  shared_preferences: ^2.0.15
  after_layout: ^1.2.0
  flutter_carousel_slider: ^1.0.8
  url_launcher: ^6.1.6
  colorful_safe_area: ^0.3.0
  flutter_riverpod: ^2.1.1
  

dev_dependencies:
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/vector1.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/vector1.jpg"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/image3.jpg
    - assets/png/
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-Bold.ttf
